<a href="https://colab.research.google.com/github/leusto/Datasets_Livro_IntMineracaoDados/blob/master/apriori.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install apyori

Collecting apyori
  Downloading apyori-1.1.2.tar.gz (8.6 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: apyori
  Building wheel for apyori (setup.py) ... done
  Created wheel for apyori: filename=apyori-1.1.2-py3-none-any.whl size=5954 sha256=7e03a86751281de38b61242eaa89eb3009480f524a0d215918a6476a6e658d7a
  Stored in directory: /root/.cache/pip/wheels/7f/49/e3/42c73b19a264de37129fadaa0c52f26cf50e87de08fb9804af
Successfully built apyori
Installing collected packages: apyori
Successfully installed apyori-1.1.2

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from apyori import apriori

In [ ]:
source1 = 'https://raw.githubusercontent.com/BejaminNaibei/dataset/main/Market_Basket_Optimisation.csv'
source2 = 'https://raw.githubusercontent.com/leusto/Datasets_Livro_IntMineracaoDados/master/apriori.csv'

In [ ]:
Data = pd.read_csv(source2, header = None)

In [ ]:
Data

         0        1        2      3
0  guarana    sabao      NaN    NaN
1  cerveja      NaN      NaN    NaN
2   fralda  cerveja      NaN    NaN
3   fralda    sabao      NaN    NaN
4   fralda  cerveja      NaN    NaN
5   fralda  cerveja    sabao    NaN
6  cerveja      NaN      NaN    NaN
7    leite   fralda  cerveja  sabao
8    sabao      NaN      NaN    NaN
9   fralda  cerveja      NaN    NaN

In [ ]:
transacts = []
# populating a list of transactions
for i in range(0, Data.shape[0]):
  transacts.append([str(Data.values[i,j]) for j in range(0, Data.shape[1])])

In [ ]:
transacts

[['guarana', 'sabao', 'nan', 'nan'],
 ['cerveja', 'nan', 'nan', 'nan'],
 ['fralda', 'cerveja', 'nan', 'nan'],
 ['fralda', 'sabao', 'nan', 'nan'],
 ['fralda', 'cerveja', 'nan', 'nan'],
 ['fralda', 'cerveja', 'sabao', 'nan'],
 ['cerveja', 'nan', 'nan', 'nan'],
 ['leite', 'fralda', 'cerveja', 'sabao'],
 ['sabao', 'nan', 'nan', 'nan'],
 ['fralda', 'cerveja', 'nan', 'nan']]

In [ ]:
supp = 0.0003
conf = 0.05
lift = 2

In [ ]:
rules_generator = apriori(transactions = transacts, min_support = supp, min_confidence = conf, min_lift = lift, min_length = 2, max_length = 2)
rules_data = list(rules_generator) # Store the results in a list
rules_data # Display the list of rules

[RelationRecord(items=frozenset({'sabao', 'guarana'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset({'guarana'}), items_add=frozenset({'sabao'}), confidence=1.0, lift=2.0), OrderedStatistic(items_base=frozenset({'sabao'}), items_add=frozenset({'guarana'}), confidence=0.2, lift=2.0)]),
 RelationRecord(items=frozenset({'sabao', 'leite'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset({'leite'}), items_add=frozenset({'sabao'}), confidence=1.0, lift=2.0), OrderedStatistic(items_base=frozenset({'sabao'}), items_add=frozenset({'leite'}), confidence=0.2, lift=2.0)])]

In [ ]:
output = rules_data # Use the stored list of rules
# putting output into a pandas dataframe
def inspect(output):
    lhs         = [tuple(result[2][0][0])[0] for result in output]
    rhs         = [tuple(result[2][0][1])[0] for result in output]
    support    = [result[1] for result in output]
    confidence = [result[2][0][2] for result in output]
    lift       = [result[2][0][3] for result in output]
    return list(zip(lhs, rhs, support, confidence, lift))
output_DataFrame = pd.DataFrame(inspect(output), columns = ['X', 'Y', 'Support', 'Confidence', 'Lift'])

In [ ]:
output_DataFrame

         X      Y  Support  Confidence  Lift
0  guarana  sabao      0.1         1.0   2.0
1    leite  sabao      0.1         1.0   2.0

In [ ]:
list(rule)

[]

Referências

https://www.kaggle.com/code/sangwookchn/association-rule-learning-with-scikit-learn/notebook

https://www.geeksforgeeks.org/implementing-apriori-algorithm-in-python/